import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-between py-6 px-12 bg-black text-white">
          <div>Greenhouse Hunter</div>
          <ul className="flex gap-12">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/dashboard">Dashboard</Link></li>
            <li><Link href="/profile">Profile</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
